name: Continuous Integration testing
on: ["push", "pull_request"]
jobs:
  build:
    name: Build BLOM on Github provided OS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        cc: [gcc]
        fc: [gfortran]
        include:
          - os: macos-10.15
            cc: [gcc-9, gcc-10]
            fc: [gfortran-9, gfortran-10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: github_action

      - name: Setup Python for newer version of Meson - Ubuntu
        uses: actions/setup-python@v2
        if: ${{ runner.os == 'Linux' }}

      - name: Install dependencies - Ubuntu
        run: sudo apt-get install -y ninja-build libnetcdff-dev gfortran
        if: ${{ runner.os == 'Linux' }}

      - name: Install dependencies - macOS
        run: brew install meson netcdf
        if: ${{ runner.os == 'macOS' }}

      - name: Install Meson - Ubuntu
        # This version of Meson should be available as an EasyBuild on Fram and
        # Betzy
        run: python -m pip install meson==0.55.1
        if: ${{ runner.os == 'Linux' }}

      - name: Setup build directory
        run: meson setup builddir
        env:
          CC: ${{ matrix.cc }}
          FC: ${{ matrix.fc }}

      - name: Compile source code
        run: meson compile -C builddir
