name: Continuous Integration testing
on: ["push", "pull_request"]
jobs:
  build:
    name: Build BLOM on Github provided OS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: meson

      - name: Setup Python for newer version of Meson
        uses: actions/setup-python@v2
        if: ${{ matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-20.04' }}

      - name: Install dependencies - Ubuntu
        run: sudo apt-get install -y ninja-build libnetcdff-dev gfortran
        if: ${{ matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-20.04' }}

      - name: Install dependencies - MacOS
        run: brew install meson gcc netcdf
        if: ${{ matrix.os == 'macos-10.15' || matrix.os == 'macos-11.0' }}

      - name: Install Meson - Ubuntu
        # This version of Meson should be available as an EasyBuild on Fram and
        # Betzy
        run: python -m pip install meson==0.55.1
        if: ${{ matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-20.04' }}

      - name: Setup build directory
        run: meson setup builddir

      - name: Compile source code
        run: meson compile -C builddir
