name: Continuous Integration testing
on: ["push", "pull_request"]
jobs:
  build:
    name: Build BLOM on Github provided OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Install dependencies - Ubuntu
        run: sudo apt-get install -y meson libnetcdff-dev gfortran
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Install dependencies - MacOS
        run: brew install meson gcc netcdf
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: meson

      - name: Setup build directory
        run: meson setup builddir

      - name: Compile source code
        run: meson compile -C builddir
