name: Continuous Integration testing
on: ["push", "pull_request"]
jobs:
  build:
    name: Build BLOM on Github provided OS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: github_action

      - name: Install dependencies - Ubuntu
        run: sudo apt-get install -y meson libnetcdff-dev gfortran
        if: ${{ runner.os == 'Linux' }}

      - name: Install dependencies - macOS
        run: brew install meson netcdf
        if: ${{ runner.os == 'macOS' }}

      - name: Setup build directory - Ubuntu
        run: meson setup builddir
        if: ${{ runner.os == 'Linux' }}

      - name: Setup build directory - macOS
        run: meson setup builddir
        if: ${{ runner.os == 'macOS' }}
        env:
          CC: gcc-10
          FC: gfortran-10

      - name: Compile source code
        run: meson compile -C builddir
